service: finvia-pay-bndes-auth

frameworkVersion: "^3"

provider:
  name: aws
  region: sa-east-1
  stage: ${opt:stage, 'dev'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource:
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/organization${self:custom.resourceSuffix}

custom:
  suffixMap:
    dev: "-dev"
    hlg: "-hlg"
    prod: ""

  resourceSuffix: ${self:custom.suffixMap.${sls:stage}}

functions:
  preTokenGeneration:
    handler: functions/pre-token-generator/index.handler
    timeout: 60
    environment:
      ORGANIZATION_TABLE: "organization${self:custom.resourceSuffix}"

resources:
  Resources:

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      DependsOn:
      - PreTokenLambdaPermission
      Properties:
        UserPoolName: "FinviaPay-bndes${self:custom.resourceSuffix}"

        UsernameAttributes:
          - email

        AutoVerifiedAttributes:
          - email

        LambdaConfig:
          PreTokenGenerationConfig:
            LambdaArn:
              Fn::GetAtt:
                - PreTokenGenerationLambdaFunction
                - Arn
            LambdaVersion: V2

        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: "FinviaPay-bndes${self:custom.resourceSuffix}"
        UserPoolId:
          Ref: CognitoUserPool

        GenerateSecret: false

        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthFlows:
          - code

        AllowedOAuthScopes:
          - openid
          - email
          - profile

        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

        CallbackURLs:
          - "http://localhost:3000/api/auth/callback"
          - "https://finvia-pay-bndes-git-hlg-finvias-projects.vercel.app/api/auth/callback"

        LogoutURLs:
          - "http://localhost:3000"
          - "https://finvia-pay-bndes-git-hlg-finvias-projects.vercel.app"

        SupportedIdentityProviders:
          - COGNITO

    CognitoUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: "finviapay-bndes${self:custom.resourceSuffix}"
        UserPoolId:
          Ref: CognitoUserPool

    PreTokenLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: PreTokenGenerationLambdaFunction
        Action: lambda:InvokeFunction
        Principal: cognito-idp.amazonaws.com

  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool
      Export:
        Name: "FinviaUserPoolId${self:custom.resourceSuffix}"

    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
      Export:
        Name: "FinviaUserPoolClientId${self:custom.resourceSuffix}"